<a href="https://colab.research.google.com/github/sanjibsinha/beginning-tensorflow-with-python/blob/main/TensorFlow_Course_Module_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
print(tf.__version__)

2.18.0


In [3]:
# Scalar (0-dimensional tensor)
scalar = tf.constant(10)
print("Scalar:", scalar)
print("Shape of scalar:", scalar.shape)
print("Data type of scalar:", scalar.dtype)

# Vector (1-dimensional tensor)
vector = tf.constant([1, 2, 3, 4, 5])
print("\nVector:", vector)
print("Shape of vector:", vector.shape)
print("Data type of vector:", vector.dtype)

# Matrix (2-dimensional tensor) - default data type is float32
matrix = tf.constant([[10, 20, 30],
                      [40, 50, 60]])
print("\nMatrix:", matrix)
print("Shape of matrix:", matrix.shape)
print("Data type of matrix:", matrix.dtype)

# Another Matrix (specify data type)
another_matrix = tf.constant([[7., 8.],
                              [9., 10.],
                              [11., 12.]], dtype=tf.float16)
print("\nAnother Matrix:", another_matrix)
print("Shape of another matrix:", another_matrix.shape)
print("Data type of another matrix:", another_matrix.dtype)

# 3-dimensional tensor
tensor_3d = tf.constant([[[1, 2, 3],
                          [4, 5, 6]],
                         [[7, 8, 9],
                          [10, 11, 12]]])
print("\n3D Tensor:", tensor_3d)
print("Shape of 3D Tensor:", tensor_3d.shape)
print("Data type of 3D Tensor:", tensor_3d.dtype)

Scalar: tf.Tensor(10, shape=(), dtype=int32)
Shape of scalar: ()
Data type of scalar: <dtype: 'int32'>

Vector: tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
Shape of vector: (5,)
Data type of vector: <dtype: 'int32'>

Matrix: tf.Tensor(
[[10 20 30]
 [40 50 60]], shape=(2, 3), dtype=int32)
Shape of matrix: (2, 3)
Data type of matrix: <dtype: 'int32'>

Another Matrix: tf.Tensor(
[[ 7.  8.]
 [ 9. 10.]
 [11. 12.]], shape=(3, 2), dtype=float16)
Shape of another matrix: (3, 2)
Data type of another matrix: <dtype: 'float16'>

3D Tensor: tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)
Shape of 3D Tensor: (2, 2, 3)
Data type of 3D Tensor: <dtype: 'int32'>


In [4]:
tensor_A = tf.constant([[1, 2], [3, 4]])
tensor_B = tf.constant([[5, 6], [7, 8]])

# Addition
add_result = tensor_A + tensor_B # or tf.add(tensor_A, tensor_B)
print("Tensor A + Tensor B:\n", add_result)

# Multiplication (element-wise)
multiply_result_elementwise = tensor_A * tensor_B # or tf.multiply(tensor_A, tensor_B)
print("\nTensor A * Tensor B (element-wise):\n", multiply_result_elementwise)

# Matrix Multiplication (this is crucial in neural networks)
# For matrix multiplication, the inner dimensions must match.
# Shape of A is (2, 2), Shape of B is (2, 2). Inner dimensions are 2 and 2 (match).
# Result shape will be (2, 2).
matmul_result = tf.matmul(tensor_A, tensor_B) # or tensor_A @ tensor_B
print("\nTensor A @ Tensor B (matrix multiplication):\n", matmul_result)

# Transposing a tensor (flipping rows and columns)
transpose_A = tf.transpose(tensor_A)
print("\nTranspose of Tensor A:\n", transpose_A)

# Try matrix multiplication with transpose
# Shape of A is (2, 2), Shape of Transpose of A is (2, 2).
# Result shape will be (2, 2).
matmul_A_transpose_A = tf.matmul(tensor_A, tf.transpose(tensor_A))
print("\nTensor A @ Transpose of Tensor A:\n", matmul_A_transpose_A)

# Create a 3D tensor and access elements (optional but good practice)
tensor_3d_slice = tensor_3d[0, :, :] # Get the first matrix
print("\nSlice of 3D Tensor (first matrix):\n", tensor_3d_slice)

tensor_3d_element = tensor_3d[1, 0, 2] # Get element at index [1, 0, 2]
print("\nElement of 3D Tensor at [1, 0, 2]:", tensor_3d_element.numpy()) # .numpy() converts tensor to NumPy array

Tensor A + Tensor B:
 tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)

Tensor A * Tensor B (element-wise):
 tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)

Tensor A @ Tensor B (matrix multiplication):
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)

Transpose of Tensor A:
 tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)

Tensor A @ Transpose of Tensor A:
 tf.Tensor(
[[ 5 11]
 [11 25]], shape=(2, 2), dtype=int32)

Slice of 3D Tensor (first matrix):
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

Element of 3D Tensor at [1, 0, 2]: 9
