<a href="https://colab.research.google.com/github/sanjibsinha/beginning-tensorflow-with-python/blob/main/tf_one.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__) # find the version number (should be 2.x+)

2.8.2


In [3]:
# rank is dimension
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Checking dimensions
scalar.ndim

0

In [5]:
vector = tf.constant([4, 7])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 7], dtype=int32)>

In [6]:
# Check the number of dimensions
vector.ndim

1

In [7]:
# Create a matrix (more than 1 dimension)
matrix = tf.constant(
    [[4, 7], 
    [5, 6]
    ]
)
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 7],
       [5, 6]], dtype=int32)>

In [8]:
print(matrix)

tf.Tensor(
[[4 7]
 [5 6]], shape=(2, 2), dtype=int32)


In [9]:
matrix.ndim

2

In [12]:
# How about a tensor? (more than 2 dimensions, although, all of the above items are also technically tensors)
tensor = tf.constant(
    [
          
           [
            [4, 7], [5, 6]
           ], 
           [
            [4, 7], [5, 6]
           ], 
           [
            [4, 7], [5, 6]
           ]
          
]
)
tensor

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[4, 7],
        [5, 6]],

       [[4, 7],
        [5, 6]],

       [[4, 7],
        [5, 6]]], dtype=int32)>

In [ ]:
tensor.ndim

3

## We will do some more tensors later